name: new_mee
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_horizontal_calendar: ^0.0.2
  auto_size_text: 3.0.0
  badges: 2.0.2
  cached_network_image: 3.1.0+1
  collection: 1.17.0
  flutter_google_places: 0.3.0
  flutter_neat_and_clean_calendar: ^0.3.4+17
  font_awesome_flutter: 10.1.0
  google_fonts: 2.2.0
  group_button: ^3.3.1
  intl: 0.17.0
  json_path: 0.3.1
  lottie: 1.2.1
  page_transition: 2.0.4
  shared_preferences: 2.0.11
  timeago: 3.1.0
  url_launcher: 6.0.15
  convert: ^3.0.1
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  get: ^4.6.1
  syncfusion_flutter_calendar: ^19.4.56
  date_time_picker: "^2.1.0"
  multiselect: ^0.0.4
  getwidget: ^3.0.1
  agora_rtc_engine: ^5.3.0
  permission_handler: ^10.0.1
  animations: ^2.0.2
  social_login_buttons: ^1.0.7
  firebase_core: ^2.4.0
  google_sign_in: ^5.3.0
  fluttertoast: ^8.1.2
  firebase_auth: ^0.6.2+1
  flutter_facebook_auth: ^3.5.0
  flutter_svg: ^1.0.3
  dart_ipify: ^1.1.1
  firebase_messaging: ^14.2.1
  firebase_messaging_web: ^3.2.11
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  image_picker: ^0.8.6
  firebase_in_app_messaging: ^0.7.0+10
  firebase_app_installations: ^0.2.1+8
  intl_phone_number_input: ^0.7.1
  libphonenumber_web: ^0.2.0+1
  emoji_picker_flutter: ^1.3.0
  emoji_chooser: ^0.9.1
  typed_data: ^1.3.0
  file_picker: ^4.6.1
  image_downloader: ^0.31.0
  image_downloader_web: ^1.0.2
  syncfusion_flutter_pdfviewer: ^19.4.56-beta
  syncfusion_flutter_pdfviewer_web: ^19.4.56-beta
  video_player_web: ^2.0.13
  quill_delta: ^2.0.0
  bottom_navy_bar: ^6.0.0
  string_validator: ^0.3.0
dev_dependencies:

  flutter_test:
    sdk: flutter
  http:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
