// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSPHw3MnOVfrtjdKJ8uI3pl31zBA9S1hs',
    appId: '1:45119442318:web:f19bd353c63958906068df',
    messagingSenderId: '45119442318',
    projectId: 'myfirstapp-72a20',
    authDomain: 'myfirstapp-72a20.firebaseapp.com',
    databaseURL: 'https://myfirstapp-72a20-default-rtdb.firebaseio.com',
    storageBucket: 'myfirstapp-72a20.appspot.com',
    measurementId: 'G-03WL4L4ST5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF7-4-Ty_Biv9-d34GGfiFz_lSbE6Q0dE',
    appId: '1:45119442318:android:9d5f9ccedb7b30de6068df',
    messagingSenderId: '45119442318',
    projectId: 'myfirstapp-72a20',
    databaseURL: 'https://myfirstapp-72a20-default-rtdb.firebaseio.com',
    storageBucket: 'myfirstapp-72a20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3BKrbuZIckMwbQqHjT2baYDKH-9eWnxs',
    appId: '1:45119442318:ios:8d1b7cdde73918cb6068df',
    messagingSenderId: '45119442318',
    projectId: 'myfirstapp-72a20',
    databaseURL: 'https://myfirstapp-72a20-default-rtdb.firebaseio.com',
    storageBucket: 'myfirstapp-72a20.appspot.com',
    iosClientId: '45119442318-encih3r0bsalpns9i9d9sinn6ff3to4t.apps.googleusercontent.com',
    iosBundleId: 'com.flutterflow.newmee',
  );
}
